import { Navbar } from './_components';
import { useFonts } from './_global-hooks';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { className } = useFonts();
  return (
    <html lang="en">
      <body className={className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
